language: php

php:
  - "7.2"
  - "7.1"

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

git:
  depth: 2147483647

cache:
  directories:
    - vendor
